# NoSwim Configuration File - Version 0.1-BETA-B1
# It is highly recommend to regenerate the config file after downloading a new version.
# To regenerate the config file: delete this config file and restart the server.

# Minimum water height (depth) to activate the sinking effect
min-water-height: 2                # Number

# Exempt players with the Water Breathing effect
water-breath-exemption: true       # Options: true, false

# Damage options: poison, drowning, or none
player-damage:
  enabled: false                   # Options: true, false
  type: poison                     # Options: poison, drowning, none
  damage-interval: 40              # Ticks (20 ticks = 1 second)

# Sinking effect
downforce:
  enabled: true                    # Toggle sinking effect on/off | Options: true, false
  amount: 0.25                     # Default sinking speed (0.1 is slower, 0.5 is faster)

# [BETA] Allow building above water
# This feature is still in development and contains bugs,
# players can easily bypass this restriction.
# It is recommended to let players build above water until the bugs are fixed.
allow-building-above-water: true   # Options: true, false (Default: true)